// commands/tmodpromos.js

const {
    SlashCommandBuilder,
    EmbedBuilder,
    ActionRowBuilder,
    ButtonBuilder,
    ButtonStyle,
    ChannelType
} = require('discord.js');

const fs = require('fs');

const EVALUATOR_ROLE = '1515133506852749493';
const TRIAL_MOD_ROLE = '1515335093319897239';

module.exports = {

    data: new SlashCommandBuilder()

        .setName('tmodpromos')

        .setDescription(
            'View Trial Moderators eligible for promotion.'
        ),

    async execute(interaction) {

        const hasRole =
            interaction.member.roles.cache.has(
                EVALUATOR_ROLE
            );

        if (!hasRole) {

            return interaction.reply({

                content:
                    '❌ You cannot use this command.',

                ephemeral: true
            });
        }

        let logs = {};

        if (fs.existsSync('./tasklogs.json')) {

            logs = JSON.parse(
                fs.readFileSync(
                    './tasklogs.json',
                    'utf8'
                )
            );
        }

        const tmods =
            interaction.guild.members.cache.filter(
                member =>
                    member.roles.cache.has(
                        TRIAL_MOD_ROLE
                    )
            );

        if (tmods.size === 0) {

            return interaction.reply({

                content:
                    '❌ No Trial Moderators found.',

                ephemeral: true
            });
        }

        const eligible = [];
        const notEligible = [];

        for (const [, member] of tmods) {

            const count =
                logs[member.id] || 0;

            if (count >= 3) {

                eligible.push({
                    member,
                    count
                });

            } else {

                notEligible.push({
                    member,
                    count
                });
            }
        }

        const embed =
            new EmbedBuilder()

                .setColor('Blue')

                .setTitle(
                    'Trial Moderator Promotions'
                )

                .setDescription(
                    `**Cycle Requirement:** 3 Logs`
                )

                .addFields(

                    {
                        name:
                            '📊 Statistics',

                        value:
                            `**Total Trial Mods:** ${tmods.size}\n` +
                            `**Eligible:** ${eligible.length}\n` +
                            `**Not Eligible:** ${notEligible.length}`
                    },

                    {
                        name:
                            '✅ Eligible',

                        value:
                            eligible.length
                                ? eligible
                                      .map(
                                          (u, i) =>
                                              `${i + 1}. ${u.member} • ${u.count}/3`
                                      )
                                      .join('\n')
                                : 'None'
                    },

                    {
                        name:
                            '❌ Not Eligible',

                        value:
                            notEligible.length
                                ? notEligible
                                      .map(
                                          (u, i) =>
                                              `${i + 1}. ${u.member} • ${u.count}/3`
                                      )
                                      .join('\n')
                                : 'None'
                    }
                )

                .setFooter({

                    text:
                        `Generated by ${interaction.user.username}`
                })

                .setTimestamp();

        const row =
            new ActionRowBuilder()

                .addComponents(

                    new ButtonBuilder()

                        .setCustomId(
                            `tmodcreate_${interaction.user.id}`
                        )

                        .setLabel(
                            'Create Promotion Threads'
                        )

                        .setStyle(
                            ButtonStyle.Success
                        )
                );

        const msg =
            await interaction.reply({

                embeds: [embed],

                components:
                    eligible.length > 0
                        ? [row]
                        : [],

                fetchReply: true
            });

        if (eligible.length === 0) return;

        const collector =
            msg.createMessageComponentCollector();

        collector.on(
            'collect',

            async i => {

                if (
                    i.customId !==
                    `tmodcreate_${interaction.user.id}`
                ) {
                    return;
                }

                const canUse =
                    i.member.roles.cache.has(
                        EVALUATOR_ROLE
                    );

                if (!canUse) {

                    return i.reply({

                        content:
                            '❌ You cannot use this button.',

                        ephemeral: true
                    });
                }

                await i.deferUpdate();

                let created = 0;

                for (const entry of eligible) {

                    try {

                        const thread =
                            await msg.startThread({

                                name:
                                    `${entry.member.user.username} - Trial Mod Promotion`,

                                autoArchiveDuration:
                                    1440,

                                type:
                                    ChannelType.PublicThread
                            });

                        await thread.send({

                            content:
                                `${entry.member}\n\nPlease complete this Trial Moderator interview.`
                        });

                        created++;

                    } catch (err) {

                        console.error(err);
                    }
                }

                const completed =
                    EmbedBuilder.from(embed)

                        .setColor('Green')

                        .addFields({

                            name:
                                'Completed',

                            value:
                                `✅ ${created} promotion thread(s) created by ${i.user}`
                        });

                const disabled =
                    new ActionRowBuilder()

                        .addComponents(

                            new ButtonBuilder()

                                .setCustomId(
                                    'created'
                                )

                                .setLabel(
                                    `Completed By ${i.user.username}`
                                )

                                .setStyle(
                                    ButtonStyle.Success
                                )

                                .setDisabled(true)
                        );

                await i.editReply({

                    embeds: [completed],

                    components:
                        [disabled]
                });
            }
        );
    }
};
